resources:
- name: team-manual-hosting-function-git
  type: git
  source:
    branch: master
    private_key: ((firebreak-q1-faas-read-only-ssh-private-key))
    uri: git@github.com:alphagov/cyber-security-team-manual-hosting-function.git
    ignored_paths: [requirements.txt, requirements-dev.txt]

- name: team-manual-hosting-function-libs-git
  type: git
  source:
    branch: master
    private_key: ((firebreak-q1-faas-read-only-ssh-private-key))
    uri: git@github.com:alphagov/cyber-security-team-manual-hosting-function.git
    paths: [requirements.txt]

- name: cyber-security-team-manual-git
  type: git
  source:
    branch: master
    private_key: ((cyber-security-team-manual-read-only-ssh-private-key))
    uri: git@github.com:alphagov/cyber-security-team-manual.git
    ignored_paths: [Gemfile, Gemfile.lock]

- name: cyber-security-team-manual-libs-git
  type: git
  source:
    branch: master
    private_key: ((cyber-security-team-manual-read-only-ssh-private-key))
    uri: git@github.com:alphagov/cyber-security-team-manual.git
    paths: [Gemfile, Gemfile.lock]

- name: team-manual-build-image
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: team-manual-build-latest

- name: team-manual-hosting-function-build-image
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: team-manual-hosting-function-build-latest

jobs:
- name: build-team-manual-image
  build_logs_to_retain: 10
  serial: true
  plan:
    - get: cyber-security-team-manual-libs-git
      trigger: true
    - get: team-manual-hosting-function-git
    - put: team-manual-build-image
      params:
        dockerfile: team-manual-hosting-function-git/terraform/team-manual-image/Dockerfile
        build: cyber-security-team-manual-libs-git

- name: build-team-manual-hosting-function-image
  build_logs_to_retain: 10
  serial: true
  plan:
    - get: team-manual-hosting-function-libs-git
      trigger: true
    - get: team-manual-hosting-function-git
    - put: team-manual-hosting-function-build-image
      params:
        dockerfile: team-manual-hosting-function-git/terraform/faas-team-manual-image/Dockerfile
        build: team-manual-hosting-function-git

- name: build-and-deploy-team-manual-to-lambda
  serial: true
  plan:
  - get: team-manual-hosting-function-git
    trigger: true
  - get: cyber-security-team-manual-git
    trigger: true

  - get: team-manual-build-image
    passed: [build-team-manual-image]

  - get: team-manual-hosting-function-build-image
    passed: [build-team-manual-hosting-function-image]

  - task: build-team-manual-static-html
    image: team-manual-build-image
    config:
      platform: linux
      run:
        path: bash
        args:
        - -c
        - |
          set -ueo pipefail
          echo "Building the Static HTML for the Team Manual"
          cp -R cyber-security-team-manual-git/* cyber-security-team-manual-build/
          cd cyber-security-team-manual-build
          bundle exec middleman build

      inputs:
        - name: cyber-security-team-manual-git
      outputs:
        - name: cyber-security-team-manual-build

  - task: build-team-manual-lambda-function
    image: team-manual-hosting-function-build-image
    config:
      platform: linux
      run:
        path: bash
        args:
        - -c
        - |
          set -ueo pipefail
          echo "Building the Python Lambda Function to Host the Team Manual"
          cp -R team-manual-hosting-function-git/* team-manual-lambda-function-builddir/
          cp -R cyber-security-team-manual-build/build/* team-manual-lambda-function-builddir/firebreakq1faas/static/
          cd team-manual-lambda-function-builddir
          make zip

      inputs:
        - name: cyber-security-team-manual-build
        - name: team-manual-hosting-function-git
      outputs:
        - name: team-manual-lambda-function-builddir

  - task: apply-terraform
    timeout: 15m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: gdsre/aws-terraform
          tag: 18.04-0.11.13
      params:
        ENV: demo
        ACCOUNT_ID: '489877524855'
        TF_VAR_oidc_client_id: ((oidc_client_id))
        TF_VAR_oidc_client_secret: ((oidc_client_secret))
        AWS_ACCESS_KEY_ID: ((demo-deploy-user-access-key))
        AWS_SECRET_ACCESS_KEY: ((demo-deploy-user-secret-access-key))
        AWS_DEFAULT_REGION: 'eu-west-2'

      run:
        path: sh
        args:
          - -c
          - |
            set -ue
            # Show what command terraform is running
            set -x
            ROOT_DIR=$(pwd)
            cd team-manual-lambda-function-builddir/terraform/firebreak-q1-event-normalisation/
            terraform init
            terraform apply -auto-approve
      inputs:
        - name: team-manual-lambda-function-builddir
