resources:
- name: firebreak-q1-faas-git
  type: git
  source:
    branch: make-image-for-ecr
    private_key: ((firebreak-q1-faas-read-only-ssh-private-key))
    uri: git@github.com:alphagov/firebreak-q1-faas.git

- name: cyber-security-team-manual-git
  type: git
  source:
    branch: master
    private_key: ((cyber-security-team-manual-read-only-ssh-private-key))
    uri: git@github.com:alphagov/cyber-security-team-manual.git

- name: team-manual-faas-image
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: team-manual-faas-latest

jobs:
- name: build-team-manual-faas-image
  build_logs_to_retain: 10
  serial: true
  plan:
    - get: firebreak-q1-faas-git
      trigger: true
    - get: cyber-security-team-manual-git
      trigger: true
    - put: team-manual-faas-image
      params:
        build: firebreak-q1-faas-git/terraform

- name: deploy-team-manual-faas
  serial: true
  plan:
  - get: firebreak-q1-faas-git
  - get: cyber-security-team-manual-git

  - task: build-team-manual-lambda
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((readonly_private_ecr_repo_url))
          tag: team-manual-faas-latest
      run:
        path: bash
        args:
        - -c
        - |
          set -ueo pipefail
          echo "Building the Static HTML for the Team Manual"
          cp -R cyber-security-team-manual-git/* cyber-security-team-manual-build/
          cd cyber-security-team-manual-build
          bundle install
          bundle exec middleman build

          echo "Building the Python Lambda Function to Host the Team Manual"
          cd ..
          cp -R firebreak-q1-faas-git/* firebreak-q1-faas-build/
          cp -R cyber-security-team-manual-build/build/* firebreak-q1-faas-build/firebreakq1faas/static/
          cd firebreak-q1-faas-build
          make zip

      inputs:
      - name: cyber-security-team-manual-git
      - name: firebreak-q1-faas-git
      outputs:
      - name: cyber-security-team-manual-build
      - name: firebreak-q1-faas-build
