resources:
- name: firebreak-q1-faas-git
  type: git
  source:
    branch: make-image-for-ecr
    private_key: ((firebreak-q1-faas-read-only-ssh-private-key))
    uri: git@github.com:alphagov/firebreak-q1-faas.git

- name: cyber-security-team-manual-git
  type: git
  source:
    branch: master
    private_key: ((cyber-security-team-manual-read-only-ssh-private-key))
    uri: git@github.com:alphagov/cyber-security-team-manual.git

- name: team-manual-faas-image
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: team-manual-faas-latest

jobs:
- name: build-team-manual-faas-image
  build_logs_to_retain: 10
  serial: true
  plan:
    - get: firebreak-q1-faas-git
      trigger: true
    - get: cyber-security-team-manual-git
      trigger: true
    - put: team-manual-faas-image
      params:
        build: firebreak-q1-faas-git/terraform
